apiVersion: v1
kind: Deployment
metadata:
  name: epics-archiver-mgmt-deployment
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: epics-archiver-mgmt
    spec:
      containers:
      - name: epics-archiver-mgmt
        image: gciotto/epics-archiver-mgmt
        ports:
        - containerPort : 11995
      restartPolicy: Always

