apiVersion: v1
kind: Service
metadata:
  name: epics-archiver-retrieval-service
spec:
  clusterIP: 10.128.1.5
  ports:
  - name: epics-archiver-retrieval-port
    port: 11998
    targetPort: 11998
  selector:
    app : epics-archiver-retrieval
