apiVersion: v1
kind: Service
metadata:
  name: epics-archiver-etl-service
spec:
  clusterIP: 10.128.1.4
  ports:
  - name: epics-archiver-etl-port
    port: 11997
    targetPort: 11997
    nodePort: 31997
  type: NodePort
  selector:
    app : epics-archiver-etl
