apiVersion: v1
kind: Service
metadata:
  name: epics-archiver-mgmt-service
spec:
  clusterIP: 10.128.1.2
  ports:
  - name: epics-archiver-mgmt-port
    port: 11995
    targetPort: 11995
    nodePort: 31995
  - name: epics-archiver-mgmt-cluster-port
    port: 12000
    targetPort: 12000
    nodePort: 32000
  type: NodePort
  selector:
    app : epics-archiver-mgmt
